server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victormartingil/cloud-config-server
          clone-on-start: true